---
name: Selenium 4

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches: [ "master" ]

env:
  MIX_ENV: test

jobs:
  selenium-v4:

    # Set up a Postgres DB service. By default, Phoenix applications
    # use Postgres. This creates a database for running tests.
    # Additional services can be defined here if required.
    services:
      db:
        image: postgres:15
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    name: Selenium V4
    runs-on: ubuntu-latest
    timeout-minutes: 5

#    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == true)

    env:
      WALLABY_DRIVER: selenium

    strategy:
      # Specify the OTP and Elixir versions to use when building
      # and running the workflow steps.
      matrix:
        otp: ['26.2.0']       # Define the OTP version [required]
        elixir: ['1.14.5']    # Define the elixir version [required]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}

    - uses: actions/cache@v1
      id: cache
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

    - run: mix local.hex --force
    - run: mix local.rebar --force

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: mix deps.get

    - name: Start Selenium
      run: java -Djava.awt.headless=true -jar "$SELENIUM_JAR_PATH" standalone > selenium-v4-${{matrix.elixir-otp.elixir}}.log 2>&1 &

    - name: elixir --erl "-detached" -S mix phx.server
      run: elixir --erl "-detached" -S mix phx.server
      env:
        MIX_ENV: test
        DB_PASSWORD: postgres
        DB_HOST: localhost
        POSTGRES_HOST: localhost



    - name: WALLABY_DRIVER=selenium mix test test/support/e2e/hello.exs
      run: WALLABY_DRIVER=selenium mix test test/support/e2e/hello.exs
      env:
        WALLABY_DRIVER: selenium
        MIX_ENV: test
        DB_PASSWORD: postgres
        DB_HOST: localhost
        POSTGRES_HOST: localhost

    - name: Run Tests
      run: mix test || mix test --failed || mix test --failed
      env:
        MIX_ENV: test
        DB_PASSWORD: postgres
        DB_HOST: localhost
        POSTGRES_HOST: localhost

    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Selenium Logs
        path: ./selenium-mac.log

